### Raiz da aplicação
GET http://localhost:5096/


### Comeco CADASTROS

### Cadastro de Clientes
POST http://localhost:5096/cliente/cadastrar
Content-Type: application/json

{
    "tipo" : "----CLIENTE----",
    "nome" : "Marcelo",
    "cpf" : "12345678901",
    "vip" : true
}

### cadastro de Funcionarios
POST http://localhost:5096/funcionario/cadastrar
Content-Type: application/json

{
    "tipo" : "----FUNCIONARIO----",
    "nome" : "Francisco",
    "cpf" : "98765432101",
    "funcao" : "Bartender"
}

### cadastro de Eventos
POST http://localhost:5096/eventos/cadastrar
Content-Type: application/json

{
    "tipo" : "----EVENTO----",
    "nome" : "Rock IHatePrograming",
    "organizacao" : "Universidade Positivo",
    "local" : "Opera de Arame",
    "estiloMusical" : "Rock"
}
### FIM CADASTROS


### Comeco Listagens


### Listagem de Clientes
GET http://localhost:5096/cliente/listar

### Listagem de Funcionarios
GET http://localhost:5096/funcionario/listar

### Listagem de Eventos
GET http://localhost:5096/eventos/listar

### Listagem de todos os cadastros
GET http://localhost:5096/listar-todos

### FIM Listagens

### Comeco exclusoes

### Excluir Cliente
DELETE http://localhost:5096/cliente/excluir/adc0e42b-c5fa-4c63-a606-b0b602ade159

### Excluir Funcionario
DELETE http://localhost:5096/funcionario/excluir/id

### Excluir Evento
DELETE http://localhost:5096/eventos/excluir/id

### FIM exclusoes 

### Comeco Alterar


### Alterar Cliente
POST http://localhost:5096/cliente/alterar/0e717deb-4100-429b-90e7-aa646549f1d4
Content-Type: application/json  

{
    "nome" : "Fanfarrao",
    "cpf" : "11223344556",  
    "vip" : false  //false or true
}// sempre deixar um espaco entre o content-type e o json....

### Alterar Funcionario
POST http://localhost:5096/funcionario/alterar/354a28a5-1f48-4bc4-88f9-8793afcd5eaa
Content-Type: application/json  

{
    "nome" : "Vladimiro Putin",
    "cpf" : "99999999999",  
    "funcao" : "Hahaha"  
}

### Alterar Evento
POST http://localhost:5096/eventos/alterar/354a28a5-1f48-4bc4-88f9-8793afcd5eaa
Content-Type: application/json  

{
    "nome" : "Baladao do Fanfarrao",
    "organizacao" : "Barriguinha's Music",  
    "Local" : "Praca Osorio",
    "estiloMusical" : "Horrivel"
}
### Fim Alterar

